#!/usr/bin/env bash
#
# Prepare the live session: create the live user, wire up display-manager
# autologin, and start whichever guest agent matches the hypervisor we are
# running under.
#
# Runs once at boot from undrabyte-live-setup.service, which is gated on
# /run/archiso — an installed system never executes this.

set -euo pipefail

readonly CONF=/etc/undrabyte/live.conf
readonly LOG_TAG=undrabyte-live-setup

log() { printf '[%s] %s\n' "$LOG_TAG" "$*"; }
warn() { printf '[%s] warning: %s\n' "$LOG_TAG" "$*" >&2; }

UNDRABYTE_LIVE_USER=forge
UNDRABYTE_LIVE_PASSWORD=forge
UNDRABYTE_LIVE_NOPASSWD_SUDO=1
UNDRABYTE_LIVE_ROOT_ENABLED=0
# shellcheck source=/dev/null
[[ -r $CONF ]] && source "$CONF"

readonly USERNAME="$UNDRABYTE_LIVE_USER"

create_user() {
    if id -u "$USERNAME" &>/dev/null; then
        log "user $USERNAME already exists"
    else
        local shell=/bin/bash
        [[ -x /usr/bin/zsh ]] && shell=/usr/bin/zsh
        useradd --create-home --shell "$shell" --comment 'UndraByte live user' "$USERNAME"
        log "created user $USERNAME"
    fi

    # Only add the groups that actually exist: the set depends on which
    # edition was built (no docker group on a --no-dev image, and so on).
    local wanted=(wheel users audio video input storage optical network
                  lp scanner games kvm libvirt docker wireshark vboxsf
                  autologin uucp rfkill)
    local add=()
    local g
    for g in "${wanted[@]}"; do
        getent group "$g" &>/dev/null && add+=("$g")
    done
    [[ ${#add[@]} -gt 0 ]] && usermod --append --groups "$(IFS=,; echo "${add[*]}")" "$USERNAME"

    printf '%s:%s\n' "$USERNAME" "$UNDRABYTE_LIVE_PASSWORD" | chpasswd

    if [[ $UNDRABYTE_LIVE_ROOT_ENABLED == 1 ]]; then
        printf 'root:%s\n' "$UNDRABYTE_LIVE_PASSWORD" | chpasswd
    else
        passwd --lock root >/dev/null
    fi

    if [[ $UNDRABYTE_LIVE_NOPASSWD_SUDO == 1 ]]; then
        install -Dm0440 /dev/stdin /etc/sudoers.d/99-undrabyte-live <<-EOF
		# Live session only. Generated by undrabyte-live-setup.service.
		%wheel ALL=(ALL:ALL) NOPASSWD: ALL
		EOF
        log "passwordless sudo enabled for wheel (live session)"
    fi
}

configure_autologin() {
    if grep -qw 'undrabyte.nodm=1' /proc/cmdline; then
        log "undrabyte.nodm=1 on the kernel command line, skipping autologin"
        return 0
    fi

    if [[ -e /usr/lib/systemd/system/sddm.service ]]; then
        install -Dm0644 /dev/stdin /etc/sddm.conf.d/10-undrabyte-autologin.conf <<-EOF
		[Autologin]
		User=$USERNAME
		Session=plasmax11.desktop
		Relogin=false

		[Theme]
		Current=breeze
		EOF
        log "sddm autologin configured for $USERNAME"
    elif [[ -e /usr/lib/systemd/system/lightdm.service ]]; then
        install -Dm0644 /dev/stdin /etc/lightdm/lightdm.conf.d/10-undrabyte-autologin.conf <<-EOF
		[Seat:*]
		autologin-user=$USERNAME
		autologin-user-timeout=0
		autologin-session=xfce
		EOF
        log "lightdm autologin configured for $USERNAME"
    else
        log "no display manager installed, console-only image"
    fi
}

start_guest_agent() {
    local virt
    virt="$(systemd-detect-virt 2>/dev/null || echo none)"
    log "hypervisor: $virt"
    case "$virt" in
        kvm|qemu)
            systemctl start spice-vdagentd.socket 2>/dev/null || true
            ;;
        oracle)
            systemctl start vboxservice.service 2>/dev/null || true
            ;;
        vmware)
            systemctl start vmtoolsd.service 2>/dev/null || true
            ;;
        microsoft)
            systemctl start hv_kvp_daemon.service hv_vss_daemon.service 2>/dev/null || true
            ;;
        none)
            log "running on bare metal"
            ;;
    esac
}

seed_home() {
    local home
    home="$(getent passwd "$USERNAME" | cut -d: -f6)"
    [[ -d $home ]] || return 0
    # /etc/skel is copied by useradd, but only for files that existed at the
    # time; re-sync so a rebuilt skel reaches an already-created user.
    cp -rn /etc/skel/. "$home/" 2>/dev/null || true
    chown -R "$USERNAME:$USERNAME" "$home"
    runuser -u "$USERNAME" -- xdg-user-dirs-update 2>/dev/null || true
}

apply_defaults() {
    # Dark by default, everywhere, before the session starts - so nobody sees
    # a white flash and then has to go hunting through settings dialogues.
    local mode=dark
    [[ -r /etc/undrabyte/theme ]] && mode="$(< /etc/undrabyte/theme)"
    if [[ -x /usr/local/bin/undrabyte-theme ]]; then
        if runuser -u "$USERNAME" -- /usr/local/bin/undrabyte-theme "$mode" &>/dev/null; then
            log "applied the $mode theme"
        else
            warn "could not apply the $mode theme"
        fi
    fi

    # Tune for whatever we turned out to be running on. Cheap, and it is the
    # difference between a snappy VM desktop and a sluggish one.
    if [[ -x /usr/local/bin/undrabyte-optimize ]]; then
        if /usr/local/bin/undrabyte-optimize apply &>/dev/null; then
            log "applied the $(systemd-detect-virt &>/dev/null && echo vm || echo bare-metal) tuning profile"
        else
            warn "optimisation profile could not be applied"
        fi
    fi
}

main() {
    create_user
    seed_home
    configure_autologin
    start_guest_agent
    apply_defaults
    log "live session ready"
}

main "$@"
